# Generated by Django 4.1.2 on 2022-10-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_question_q_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
    ]
