# Generated by Django 4.1.2 on 2022-10-21 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_question_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='q_type',
            new_name='question_type',
        ),
    ]
