# Generated by Django 4.1.2 on 2022-10-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('radio', 'radio'), ('checkbox', 'checkbox')], max_length=200, null=True),
        ),
    ]
