# Generated by Django 4.1.2 on 2022-10-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='otherField',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
