# Generated by Django 4.1.2 on 2022-10-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_question_otherfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='otherField',
            field=models.CharField(default=False, max_length=200, null=True),
        ),
    ]
