# Generated by Django 4.1.2 on 2022-10-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_question_otherfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='giveOtherField',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
