# Generated by Django 4.1.2 on 2022-10-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_question_giveotherfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('radio', 'radio'), ('checkbox', 'checkbox')], max_length=200, null=True),
        ),
    ]
