# Generated by Django 4.1.2 on 2022-10-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='otherField',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
