# Generated by Django 4.1.2 on 2022-10-21 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_question_otherfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='otherField',
        ),
        migrations.AddField(
            model_name='question',
            name='showOtherField',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OtherField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherField', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.survey')),
            ],
        ),
    ]
