# Generated by Django 4.1.2 on 2022-11-02 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_option_vote_alter_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='vote',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BinaryField(default=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.survey')),
            ],
        ),
    ]
