# Generated by Django 4.1.2 on 2022-11-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_option_vote_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.BooleanField(default=True),
        ),
    ]
